[package]
name = "poly_checkpoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rs_merkle = { version = "1.4", default-features = false }
sha3 = "0.10.8"
